### ISSUE TITLE
remappings.txt src/ entry causes problems

### ISSUE THREAD

**Issue by aathan** [PaulRBerg/prb-contracts#40]
I'm not sure why the `src/=src/` entry in remappings.txt is necessary. However, it currently causes problems when prb-contracts is used a lib/ component in a foundry project, because any imports in the main project tend to resolve to relative-from-base-of-project paths that start with `src/` and for whatever reason, foundry's invocation of solc must incorporate the remappings.txt of prb-contracts in such a way that this ends up now attempting to import from prb-contracts. I've reported this to the foundry project, and the "right" solution may end up being that they need to translate the remappings.txt of dependencies before using those to build the solc remappings; or, perhaps this problematic entry can be removed from your project? Removing it manually after the git submodule fetch seems to work ok FYI.

**Comment by PaulRBerg** [comment]
This is a known bug in Foundry: https://github.com/foundry-rs/foundry/issues/3440

It's not that it's necessary (`forge build` and `forge test` work without it), but that adding it makes VSCode's [Go to Definition](https://twitter.com/JJordan/status/1593699655380074496) work. So it's unfortunate that projects like PRBContracts cannot use the `src/=src` remapping because of this bug.

Anyway, I agree that it makes sense to remove `src/=src/` from this repo's remappings for now.

**Comment by PaulRBerg** [comment]
Fixed via #41.
