### ISSUE TITLE
Include the Hardhat artifacts and the TypeChain bindings in the npm package

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-contracts#7]

**Comment by paulrberg** [comment]
Added script that does this in [848393a](https://github.com/paulrberg/contracts/commit/848393a026f87739b4cfb3b18891dff9180ff017).

**Comment by paulrberg** [comment]
Re-opening this as it's not as easy as I initially thought. The core issue is that the name of the package is `@paulrberg/contacts`. Because of this, I consider the `contracts` folder the root of the package, not the actual root of the repo, which is more like the root of the development environment. The `artifacts` and the `typechain` folders are located at the same level with `contracts`.

One possible remedy is to move the npm-ready `artifacts` and the `typechain` folder in `contracts`, but git ignore them.

**Comment by PaulRBerg** [comment]
No longer applicable as this repo has been refactored to use Foundry and has no JavaScript/ TypeScript anymore.
